services:
  lab_service:
    image: ${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: lab_service
    ports:
      - "8000:8000"
    environment:
      - SERVICE_NAME=single-container
    restart: unless-stopped
    

  two_lab_service:
    image: ${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: two_lab_service
    ports:
      - "8001:8000"
    environment:
      - SERVICE_NAME=single-container
    restart: unless-stopped
    
  three_lab_service:
    image: ${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: three_lab_service
    ports:
      - "8002:8000"
    environment:
      - SERVICE_NAME=single-container
    restart: unless-stopped
    
